version: '3.9'

services:
  budget-daemon:
    build: .
    working_dir: /app
    volumes:
      # Persist budget data; BUDGET_CACHE_DIR is loaded from .env for substitution
      - type: bind
        source: ${BUDGET_CACHE_DIR}
        target: /app/data
    env_file:
      - .env
    environment:
      - BUDGET_CACHE_DIR=/app/data
    command: npm start
