version: '3.9'

services:
  budget-daemon:
    build: .
    image: actual-budget-daemon:latest
    working_dir: /app
    volumes:
      # Persist data (model, budget, etc.) in the data directory
      - type: bind
        source: ./data
        target: /app/data
    env_file:
      - .env
    command: npm start
