version: '3.9'

services:
  budget-daemon:
    build: .
    image: actual-budget-daemon:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ${ACTUAL_DATA_DIR}:${ACTUAL_DATA_DIR}
    env_file:
      - .env
    command: npm start
