version: '3.9'

services:
  budget-daemon:
    image: ghcr.io/rjlee/actual-test:latest
    container_name: actual-budget-daemon
    restart: unless-stopped
    # Optional mapping of your Actual Budget server hostname back to localhost
    extra_hosts:
      - '${OPTIONAL_EXTRA_HOST}'
    volumes:
      # Persist budget data; BUDGET_CACHE_DIR is loaded from .env for substitution
      - type: bind
        source: ${BUDGET_CACHE_DIR}
        target: /app/data
    env_file:
      - .env
    environment:
      - BUDGET_CACHE_DIR=/app/data
    command: npm start
